### PR TITLE
Resolve runtime version from local openshift

### PR DESCRIPTION
**Pull request by djzager**
Update the local openshift adapter to read the runtime version off of
the image.

### CODE REVIEW

**Comment by djzager** [comment]
It is worth noting that `apb push` without using the openshift internal registry does not work at this time:

```
[2017-12-06T21:14:36.277Z] [DEBUG] handler::apbAddSpec
[2017-12-06T21:14:36.277Z] [DEBUG] Successfully decoded pushed spec:
[2017-12-06T21:14:36.277Z] [DEBUG] version: 1.0
name: hello-world-apb
description: deploys hello-world web application
bindable: False
async: optional
metadata:
  displayName: Hello World Mine (APB)
  longDescription: A sample APB which deploys a containerized Hello World web application
  dependencies: ['docker.io/ansibleplaybookbundle/hello-world:latest']
  providerDisplayName: "Red Hat, Inc."
plans:
  - name: default
    description: A sample APB which deploys Hello World
    free: True
    metadata:
      displayName: Default
      longDescription: This plan deploys a Python web application displaying Hello World
      cost: $0.00
    parameters: []

[2017-12-06T21:14:36.278Z] [DEBUG] Unmarshalled into apb.Spec:
[2017-12-06T21:14:36.278Z] [DEBUG] {ID: Runtime:0 Version:1.0 FQName:hello-world-apb Image: Tags:[] Bindable:false Description:deploys hello-world web application Metadata:map[displayName:Hello World Mine (APB) longDescription:A sample APB which deploys a containerized Hello World web application dependencies:[docker.io/ansibleplaybookbundle/hello-world:latest] providerDisplayName:Red Hat, Inc.] Async:optional Plans:[{ID: Name:default Description:A sample APB which deploys Hello World Metadata:map[displayName:Default longDescription:This plan deploys a Python web application displaying Hello World cost:$0.00] Free:true Bindable:false Parameters:[] BindParameters:[] UpdatesTo:[]}]}
```
I'm not certain the best way to address this.

**Comment by djzager** [comment]
[Improve Ansible Broker's Bind Credential Extraction Process](https://trello.com/c/rT9jfi2P/583-improve-ansible-brokers-bind-credential-extraction-process)

**Comment by rthallisey** [comment]
> It is worth noting that apb push without using the openshift internal registry does not work at this time:
>
Can you explain this further?  I think I remember you mentioning it on a call.

**Comment by djzager** [comment]
> Can you explain this further? I think I remember you mentioning it on a call.

@rthallisey when we perform an `apb push` that doesn't use the internal openshift registry, we simply communicate with the broker 1) the name of our image and 2) the contents of our apb.yml. There is no `com.redhat.apb.runtime` label to inspect.

We **could** update the `apb push` command to also send along the runtime version **OR** we could come up with a whole new way that we would like for it to work in the kubernetes case with no internal registry. Either way, this PR doesn't fix those issues.

**Comment by rthallisey** [comment]
We don't have to pass along a runtime since every new apb is going to use the secret for bind creds. Then we would have to default the runtime to 2 in the broker.

**Comment by djzager** [comment]
That doesn't seem unreasonable. We can't really trust that people won't try and push a v1 runtime image but if we warn on the push that we are assuming the runtime version...then I could be down with that change.

**Comment by rthallisey** [comment]
If you pull the latest apb-ansible-module you will always get runtime 2. So if you are on a runtime 1 label and you rebuild your container, it should update to the runtime 2 ansible module.  A warning on the apb tool side would be good.

> We can't really trust that people won't try and push a v1 runtime image 
>
Would you have to install a specific package version of the asb module?

**Comment by djzager** [comment]
The `ansible-asb-modules` do not have the label, the [apb-base image has the label](https://github.com/ansibleplaybookbundle/apb-base/blob/master/Dockerfile-canary#L3). The apb tool does not do any inspection of the `FROM:` line of the Dockerfile before building it and I don't know if the apb tool uses the `--no-cache` option when building the image (this would make it possible for you to have a cached version of apb-base and use that).

This is a development endpoint, so it is __okay__ if it doesn't work because you messed up, but there are a number of ways that we could __think__ that we are looking at a runtime 2 when it is not. I just don't want that fact to go unnoticed if I'm going to update the broker to handle `apb push`.

**Pull request merged**
