### PR TITLE
Convert YAML to JSON before using JSON tags

### PR DESCRIPTION
**Pull request by rthallisey**
First translate YAML to JSON before unmarshaling to a structure with JSON tags. This is less prone to error.

### CODE REVIEW

**Comment by jmrodri** [comment]
What was the reason behind this PR? IIRC the decoded string is in YAML. We are able to decode yaml into structures quite easily. We can even add ``yaml:"fieldname"`` similar to how we do the json stuff.

**Comment by rthallisey** [comment]
I was passing around a large set of yaml as a config file and found this issue.  I think the YAML to JSON has trouble with complex YAML structures so this was to guarantee we never have that issue.

**Comment by rthallisey** [comment]
@jmrodri does that address your question?

**Comment by jmrodri** [comment]
@rthallisey what large yaml were you passing around? How large of a yaml file was it to cause the problem? Right now things are working as is, unless you can show me what problem this fixes.

**Comment by jmrodri** [comment]
NACK

**Comment by eriknelson** [comment]
Maybe we should log an issue with the problematic yaml and investigate that directly?

**Comment by rthallisey** [comment]
Let me dig up what I was using.  It wasn't bad yaml, but the information was nested 3 or 4 layers down and was never being gathered.   All I'm doing is converting all incoming data, yaml and json, and decoding with the json decoder. Kubernetes does the same thing.  That's where I got the idea from.

https://github.com/kubernetes/apimachinery/blob/4500b7d1a0fc94ffb6d03f4019b2968b47e165bf/pkg/runtime/serializer/json/json.go#L87

**Comment by shawn-hurley** [comment]
Have we seen an issue during the last iteration with this? 
[This](http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/) makes it seem like the real problem is attempting to serialize json and yaml into the same struct. Specs are taken in as YAML and output as JSON. Because of this, I think it might make sense to convert it to all one format to interact with the struct.

**Comment by jmrodri** [comment]
I see the comments in the blog, but I struggle because we've been running for months without a problem in any of the areas where we do yaml conversion. If there was a problem we saw consistently I would be much less of a pain with this simple PR.

Now if we really want to do this then, there are quite a few uses of `yaml.Unmarshal` that need to be replaced then. 

```
$ git grep "yaml.Unmarshal"         
cmd/mock-registry/mock_registry.go:     yaml.Unmarshal(dat, &parsedDat)            
pkg/apb/mock_registry.go:       err = yaml.Unmarshal(specYaml, &parsedData)        
pkg/apb/types.go:       if err = yaml.Unmarshal([]byte(payload), obj); err != nil {
pkg/app/config.go:      if err = yaml.Unmarshal(dat, &config); err != nil {        
```

**Comment by jmrodri** [comment]
@eriknelson thoughts?

**Comment by jmrodri** [comment]
this also needs rebasing since there are conflicts.

**Comment by jmrodri** [comment]
@jmontleon this PR would add a new dependency.

**Comment by eriknelson** [comment]
Sorry guys, needed to catch up on this one.

My current feelings are, I'm still averse to moving from yaml -> json -> struct. golang (or whatever lang) *should* be entirely agnostic after that text runs through a processor. Maybe that's not fair, because [yaml is a technical superset of json](https://stackoverflow.com/a/1729545), but we're not doing anything in our yaml specs that deserve loss in a conversion to json.

Fundamentally, I don't think the data rep should matter from a broker perspective, and it shouldn't dictate broker code.

I'm okay with adopting it if it necessary, but I want to capture limitations of the yaml parser and log issues where they need to be logged, because yaml alone should be sufficient if it's a true superset of json.

**Comment by eriknelson** [comment]
@rthallisey Do we want to close this and reopen if we come across the problem again, or were you working on that so we should leave this open?

**Comment by rthallisey** [comment]
I wanted to see if I could generate the yaml that gave me the issue. Since what we have works, let's stick with it and we can always come back to this if there's a problem.

**Pull request closed without merging**
