### PR TITLE
Proposal: CI Framework

### PR DESCRIPTION
**Pull request by rthallisey**
New CI framework proposal.

### CODE REVIEW

**Comment by jmontleon** [comment]
I like the idea. Will there be a way to input values when necessary as well? For instance, for mediawiki you need to specify a password and there is no default. In this case it seems the there would need to be a way to address this in input.

**Comment by rthallisey** [comment]
@jmontleon I forgot to address config. Thanks for pointing that out.

In order to keep the CI yaml as simple as possible, I was thinking we could have a default location to drop and APB config file.  Since each APB will have it's own git repo, we can curl the location of any config we need.  I think this is a good way to start since it's simple. As things progress, we could always add config override or custom config file locations.

There's also @shawn-hurley's work with the test apb playbook and that playbook will have a set of defaults. Maybe we can share those defaults?

**Comment by shawn-hurley** [comment]
I have a general question here, what are we attempting to verify with this CI? 
Are trying to make sure that the APB's are good to be published or are we trying to verify that the ASB can deploy and manage a configurable setup of APBs? Alternatively, verifying a third option that I am not aware of.

**Comment by rthallisey** [comment]
This is to replace the existing CI we have, which does a provision and bind test between mediawiki and postgresql. 

The goal is to cover: ```ASB can deploy and manage a configurable setup of APBs```, but it can also tell us: ```APB's are good to be published```.

**Comment by shawn-hurley** [comment]
> ASB can deploy and manage a configurable setup of APBs

Makes complete sense for this. 
> APB's are good to be published

This should be covered by the `test` action that we have defined. I think that makes more sense. These are going to be doing the same basic things, running a configurable number of actions on an APB. The benefit of this PR is that we can have two APBs interact while running the configurable number of actions, which IMO should be a test of the broker and should tell us nothing of the APBs status. 

> Each APB repo will have a config file for running a CI job.

This to me still feels wrong. I think the APB should be able to be tested independently of any service catalog/service broker for it's CI. The requirement that we make an APB test with specific other APBs, IMO, takes away from their generic nature (until we get to have dependencies). Also, in your example you're requiring and APB that has set bindable to false, to test the binding of a database APB. Which would we mark as failed if binding failed?  I think this can be easily remedied by moving the configuration out of the APB repo.

>There's also @shawn-hurley's work with the test apb playbook and that playbook will have a set of defaults. Maybe we can share those defaults?

I agree, we will need to add to the test documentation, that there is a specific default location, and will need to add some sort of mechanism for passing those in on certain actions, but yes this makes total sense to me.

**Comment by rthallisey** [comment]
>>  APB's are good to be published
>>
> This should be covered by the test action that we have defined. I think that makes more sense. These 
> are going to be doing the same basic things, running a configurable number of actions on an APB. .
>
I agree with what your saying.  The goal of this framework is to enable complex testing.  But, basic testing is unavoidable when doing complex testing.  In the gate, the mediawiki and postgresql CI completely covers all of the smoke tests for mediawiki and postgresql. It's unavoidable.  The difference between this in the test playbook is that the playbook is portable and this CI sits in the repo. They are different use cases.
> The benefit of this PR is that we can have two APBs interact while running the configurable number of 
> actions, which IMO should be a test of the broker and should tell us nothing of the APBs status
>
I slightly disagree. It does tell us the APBs status, but only in the master branch. It does not tell us the status of any published APB image you pull from dockerhub. That's where the test playbook will give you a status because it's shipped with the APB code while the framework is not.

**Comment by rthallisey** [comment]
>   Each APB repo will have a config file for running a CI job.
>
>> This to me still feels wrong. I think the APB should be able to be tested independently of any
>> service catalog/service broker for it's CI. 
>>
I think it's great to have APBs be independently tested from the catalog and broker, but it will improve our coverage if we also supplement that by testing with the broker and catalog.  I would like test bind, multi APB apps, and whether one APB works with another.
>> The requirement that we make an APB test with specific
>> other APBs, IMO, takes away from their generic nature (until we get to have dependencies). 
>>
The framework is designed to make it really easy to test with other APBs, but it's not a requirement.  The point of making it easy is to encourage APB developers to do it so we improve our CI testing.
>> Also, in your example you're requiring and APB that has set bindable to false, to test the binding of
>> a database APB. Which would we mark as failed if binding failed? I think this can be easily
>> remedied by moving the configuration out of the APB repo.
>>
The are no requirement that the APB does not itself impose. So if the APB can't bind to anything and tries to it will fail as expected.

**Comment by rthallisey** [comment]
Spoke with @shawn-hurley.  To summarize our conversation:
 1) We want to try and reuse test.yml with the CI framework if possible.
 2) There's overlap with the test.yml work, but the CI framework will test APB using the broker and catalog while the test.yml is a portable smoketest.
 3) We want apb devs to use both the smoke test and CI framework when building new APBs.

**Pull request merged**
