### PR TITLE
Remove upgrade from Ubuntu 14.0 to 16.04

### PR DESCRIPTION
**Pull request by rthallisey**
**Describe what this PR does and why we need it**:
This should speed up the openshift job!

### CODE REVIEW

**Comment by jmrodri** [comment]
I thought we put this upgrade in to fix a problem. Is this problem no longer an issue?

**Comment by rthallisey** [comment]
@jmrodri it was fixed in new versions of kubernetes.

**Comment by rthallisey** [comment]
CI on the master branch has been having issues lately.  The issue isn't related to this PR because the upgrade fixed oc cluster up failing on the service-catalog stating

**Comment by jmrodri** [comment]
If removing the upgrade will move us towards fixing CI, then ACK. I just didn't want to undo something doen to solve a previous issue without knowing if said issue has been addressed. Sounds like it has.

**Pull request merged**
