### PR TITLE
Update run_latest_build w/ origin latest default

### PR DESCRIPTION
**Pull request by djzager**
Make the run latest script run the latest origin (by default) while supporting `v3.6.0`.

### CODE REVIEW

**Comment by djzager** [comment]
@karmab may be interested in having a look also

**Comment by jmrodri** [comment]
@djzager what should I be on the lookout for?

**Comment by jmrodri** [comment]
I must be doing something wrong.

```
[jesusr@speed3 ansible-service-broker{djzager-37-run-latest}]$ ./scripts/run_latest_build.sh 
Starting OpenShift using docker.io/openshift/origin:latest ...
OpenShift server started.

The server is accessible via web console at:
    https://172.17.0.1.nip.io:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

Logged into "https://127.0.0.1:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-service-catalog
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-template-service-broker

Using project "myproject".
Now using project "ansible-service-broker" on server "https://127.0.0.1:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.
service "asb" created
serviceaccount "asb" created
clusterrolebinding "asb" created
clusterrole "asb-auth" created
clusterrolebinding "asb-auth-bind" created
clusterrole "access-asb-role" created
persistentvolumeclaim "etcd" created
deploymentconfig "asb" created
secret "asb-auth-secret" created
configmap "broker-config" created
serviceaccount "ansibleservicebroker-client" created
clusterrolebinding "ansibleservicebroker-client" created
secret "ansibleservicebroker-client" created
route "asb-1338" created
servicebroker "ansible-service-broker" created
[jesusr@speed3 ansible-service-broker{djzager-37-run-latest}]$ oc get pods
NAME          READY     STATUS    RESTARTS   AGE
asb-1-8zj97   0/2       Pending   0          1m
asb-1-l0bk5   0/2       Evicted   0          1m
```

**Comment by jmrodri** [comment]
I see no APBs
website

**Comment by djzager** [comment]
It stinks @jmrodri but I'm not so certain about what I was looking at yesterday. I thought your issue was related to your oc client version but I'm running into issues attempting to recreate yours. I'm adding the WIP and `do-not-merge` until I have them figured out.

**Comment by djzager** [comment]
# 3.6 Testing

## First the version

```
➜  ansible-service-broker git:(37-run-latest) ✗ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

## Run latest

```
➜  ansible-service-broker git:(37-run-latest) ✗ ORIGIN_VERSION=v3.6.0 bash -x scripts/run_latest_build.sh
++ ip addr show docker0
++ grep -Po 'inet \K[\d.]+'
+ DOCKER_IP=172.17.0.1
+ PUBLIC_IP=172.17.0.1
+ HOSTNAME=172.17.0.1.nip.io
+ ROUTING_SUFFIX=172.17.0.1.nip.io
+ ORIGIN_IMAGE=docker.io/openshift/origin
+ ORIGIN_VERSION=v3.6.0
+ oc cluster up --image=docker.io/openshift/origin --version=v3.6.0 --service-catalog=true --routing-suffix=172.17.0.1.nip.io --public-hostname=172.17.0.1.nip.io
Starting OpenShift using docker.io/openshift/origin:v3.6.0 ...
OpenShift server started.
...

+ oc login -u system:admin
Logged into "https://127.0.0.1:8443" as "system:admin" using existing credentials.
...

+ TEMPLATE_URL=https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
+ DOCKERHUB_USER=changeme
+ DOCKERHUB_PASS=changeme
+ DOCKERHUB_ORG=ansibleplaybookbundle
+ ENABLE_BASIC_AUTH=true
+ '[' v3.6.0 = latest ']'
++ echo -e '{"basicAuthSecret":{"namespace":"ansible-service-broker","name":"asb-auth-secret"}}'
+ BROKER_AUTH='{"basicAuthSecret":{"namespace":"ansible-service-broker","name":"asb-auth-secret"}}'
+ VARS='-p BROKER_KIND=Broker         -p BROKER_AUTH={"basicAuthSecret":{"namespace":"ansible-service-broker","name":"asb-auth-secret"}}'
+ curl -s https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
+ oc create -f -
+ oc process -n ansible-service-broker -p DOCKERHUB_USER=changeme -p DOCKERHUB_PASS=changeme -p DOCKERHUB_ORG=ansibleplaybookbundle -p ENABLE_BASIC_AUTH=true -p BROKER_KIND=Broker -p 'BROKER_AUTH={"basicAuthSecret":{"namespace":"ansible-service-broker","name":"asb-auth-secret"}}' -f -
service "asb" created
serviceaccount "asb" created
clusterrolebinding "asb" created
clusterrole "asb-auth" created
clusterrolebinding "asb-auth-bind" created
clusterrole "access-asb-role" created
persistentvolumeclaim "etcd" created
deploymentconfig "asb" created
secret "asb-auth-secret" created
configmap "broker-config" created
serviceaccount "ansibleservicebroker-client" created
clusterrolebinding "ansibleservicebroker-client" created
secret "ansibleservicebroker-client" created
route "asb-1338" created
broker "ansible-service-broker" created
+ '[' 0 -ne 0 ']'
```

### I swear it works

```
➜  ansible-service-broker git:(37-run-latest) ✗ oc get brokers -o yaml
...
- apiVersion: servicecatalog.k8s.io/v1alpha1
  kind: Broker
  metadata:
    creationTimestamp: 2017-10-04T13:58:55Z
    finalizers:
    - kubernetes-incubator/service-catalog
    name: ansible-service-broker
    namespace: ""
    resourceVersion: "23"
    selfLink: /apis/servicecatalog.k8s.io/v1alpha1/brokersansible-service-broker
    uid: 29458c4d-a90c-11e7-9ac7-0242ac110002
  spec:
    authInfo:
      basicAuthSecret:
        name: asb-auth-secret
        namespace: ansible-service-broker
    url: https://asb.ansible-service-broker.svc:1338/ansible-service-broker/
  status:
    conditions:
    - lastTransitionTime: 2017-10-04T13:59:25Z
      message: Successfully fetched catalog entries from broker.
      reason: FetchedCatalog
      status: "True"
      type: Ready

➜  ansible-service-broker git:(37-run-latest) ✗ oc get pods
NAME          READY     STATUS    RESTARTS   AGE
asb-1-0jp7j   2/2       Running   1          58s
```

20171004_100252_scrot

**Comment by djzager** [comment]
# 3.7 Testing

## OC Client Version

```
➜  ansible-service-broker git:(37-run-latest) ✗ oc version
oc v3.7.0-alpha.1+1ca3fb5-839
kubernetes v1.7.0+80709908fd
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

## Run Latest

```
➜  ansible-service-broker git:(37-run-latest) ✗ bash -x scripts/run_latest_build.sh
++ ip addr show docker0
++ grep -Po 'inet \K[\d.]+'
+ DOCKER_IP=172.17.0.1
+ PUBLIC_IP=172.17.0.1
+ HOSTNAME=172.17.0.1.nip.io
+ ROUTING_SUFFIX=172.17.0.1.nip.io
+ ORIGIN_IMAGE=docker.io/openshift/origin
+ ORIGIN_VERSION=latest
+ oc cluster up --image=docker.io/openshift/origin --version=latest --service-catalog=true --routing-suffix=172.17.0.1.nip.io --public-hostname=172.17.0.1.nip.io
Starting OpenShift using docker.io/openshift/origin:latest ...
OpenShift server started.

+ oc login -u system:admin
Logged into "https://127.0.0.1:8443" as "system:admin" using existing credentials.
...

+ TEMPLATE_URL=https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
+ DOCKERHUB_USER=changeme
+ DOCKERHUB_PASS=changeme
+ DOCKERHUB_ORG=ansibleplaybookbundle
+ '[' latest = latest ']'
+ ENABLE_BASIC_AUTH=false
++ oc get secret -n kube-service-catalog -o 'go-template={{ range .items }}{{ if eq .type "kubernetes.io/service-account-token" }}{{ index .data "service-ca.crt" }}{{end}}{{"\n"}}{{end}}'
++ tail -n 1
+ VARS='-p BROKER_CA_CERT=LS0tlongstring='
+ curl -s https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
+ oc create -f -
+ oc process -n ansible-service-broker -p DOCKERHUB_USER=changeme -p DOCKERHUB_PASS=changeme -p DOCKERHUB_ORG=ansibleplaybookbundle -p ENABLE_BASIC_AUTH=false -p BROKER_CA_CERT=LS0tlongstring= -f -
service "asb" created
serviceaccount "asb" created
clusterrolebinding "asb" created
clusterrole "asb-auth" created
clusterrolebinding "asb-auth-bind" created
clusterrole "access-asb-role" created
persistentvolumeclaim "etcd" created
deploymentconfig "asb" created
secret "asb-auth-secret" created
configmap "broker-config" created
serviceaccount "ansibleservicebroker-client" created
clusterrolebinding "ansibleservicebroker-client" created
secret "ansibleservicebroker-client" created
route "asb-1338" created
servicebroker "ansible-service-broker" created
+ '[' 0 -ne 0 ']'
```

## I swear it works

```
➜  ansible-service-broker git:(37-run-latest) ✗ oc get servicebrokers -o yaml
...
- apiVersion: servicecatalog.k8s.io/v1alpha1
  kind: ServiceBroker
  metadata:
    creationTimestamp: 2017-10-04T14:33:06Z
    finalizers:
    - kubernetes-incubator/service-catalog
    generation: 1
    name: ansible-service-broker
    namespace: ""
    resourceVersion: "56"
    selfLink: /apis/servicecatalog.k8s.io/v1alpha1/servicebrokers/ansible-service-broker
    uid: f001d200-a910-11e7-83f7-0242ac110004
  spec:
    authInfo:
      bearer:
        secretRef:
          kind: Secret
          name: ansibleservicebroker-client
          namespace: ansible-service-broker
    caBundle: LS0tlongstring=
    relistBehavior: Duration
    relistDuration: 15m0s
    relistRequests: 0
    url: https://asb.ansible-service-broker.svc:1338/ansible-service-broker/
  status:
    conditions:
    - lastTransitionTime: 2017-10-04T14:33:26Z
      message: Successfully fetched catalog entries from broker.
      reason: FetchedCatalog
      status: "True"
      type: Ready
    reconciledGeneration: 1

➜  ansible-service-broker git:(37-run-latest) ✗ oc get pods
NAME          READY     STATUS    RESTARTS   AGE
asb-1-7q223   2/2       Running   1          1m
```
20171004_103502_scrot

**Comment by jmrodri** [comment]
```
[jesusr@speed3 ansible-service-broker{djzager-37-run-latest}]$ bash -x ./scripts/run_latest_build.sh 
++ ip addr show docker0
++ grep -Po 'inet \K[\d.]+'
+ DOCKER_IP=172.17.0.1
+ PUBLIC_IP=172.17.0.1
+ HOSTNAME=172.17.0.1.nip.io
+ ROUTING_SUFFIX=172.17.0.1.nip.io
+ ORIGIN_IMAGE=docker.io/openshift/origin
+ ORIGIN_VERSION=latest
+ oc cluster up --image=docker.io/openshift/origin --version=latest --service-catalog=true --routing-suffix=172.17.0.1.nip.io --public-hostname=172.17.0.1.nip.io
Starting OpenShift using docker.io/openshift/origin:latest ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for docker.io/openshift/origin:latest image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 127.0.0.1 as the server IP
-- Checking service catalog version requirements ... OK
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... 
   scc "privileged" added to: ["system:serviceaccount:default:registry"]
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Importing service catalog templates ... OK
-- Installing service catalog ... FAIL
   Error: failed to start the service catalog apiserver: timed out waiting for the condition
+ oc login -u system:admin
Logged into "https://127.0.0.1:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default
    kube-public
    kube-service-catalog
    kube-system
    openshift
    openshift-infra

Using project "default".
+ oc new-project ansible-service-broker
Now using project "ansible-service-broker" on server "https://127.0.0.1:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.
+ TEMPLATE_URL=https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
+ DOCKERHUB_USER=jmrodri
+ DOCKERHUB_PASS=HIkyoiHirHi1
+ DOCKERHUB_ORG=ansibleplaybookbundle
+ '[' latest = latest ']'
+ ENABLE_BASIC_AUTH=false
++ oc get secret -n kube-service-catalog -o 'go-template={{ range .items }}{{ if eq .type "kubernetes.io/service-account-token" }}{{ index .data "service-ca.crt" }}{{end}}{{"\n"}}{{end}}'
++ tail -n 1
+ VARS='-p BROKER_CA_CERT=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTFNRGN3T0RRek1qTXdIaGNOTVRjeE1EQTBNREl6TWpBeVdoY05Nakl4TURBegpNREl6TWpBeldqQW1NU1F3SWdZRFZRUUREQnR2Y0dWdWMyaHBablF0YzJsbmJtVnlRREUxTURjd09EUXpNak13CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN4UDh0Z2ZNV1MzQm1KOGhGSE9IQUEKY0hrRzVHWWczaTYwYVVEZTlENU5nNXJXZlZsSkVnZUhwaWtVeXFnbTVBUVdJeThKZE5kbW85c2QzdEluc0RxMAp2QndyRzBUU1YzaWQ4TlpmVjJ5aTZFdVBxSTVIeGtJQUFaYXM3Y1RlYjlxRC9QVEhQSVlWcy9sdjlsb24zUlV1CnhGZ3RaQU5HcW1XRW9raHkyYnd0MDVDSFdVYUp0cUZGMHM2MzBEajRLbW9XMkpuZUF5cGNlSGlUMDNTZ1JneEcKdmhKbVRaVm53MEVqckVvRUtYTHM1eXdlNk1OT0NUYTh4Ymdkd0hZNHZDb0Uva2I2NFJvelY1cTllSDRkSGFSNQpwZzNMTWVQenBKS1czc1FXbFZjYU9peTNvaGozZkR2emdjMkwxcEJ5TVc2YWN4SlQwcnhnSDlnYmNvSEc2TTg1CkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQXlHWm1pM1NXNHVTUW84cENvNktGL05rejlOSHNhY0lEOHRNdXJUSVczM0VPMwpGY2xNQ0E2RHdwOEs1SFBQdkhUMFJXYWRzczNkWlFoTGFBUFdua0NmVFFidndma2FIdjMvaGN0N2lvWGJHd1pRCk9oODQvUWtGdnRGcU04Mm50eWtCbGcxenFiaHErWVM0K1RNa0VIQWZpL1AwOVpBY2NCdnZybzMzdldXcWFvdDEKQkpGbDM4RjRTdk5vQURmOXRTWFZ5aENpWFl4N3RMQTBUL0tQYnRUUEpTR0tUbW82QzIyaFRqQVZtQkR1S3ZrMwoxUGtTNHVJdklxSnB3RWtjUDB4dzVsZUZyNnVZakN5NCt5azFhdU4vYlhscjFPVERjTC9vUlp1WFluVVhxRkdxCnRIazFSMXlZTHB2bUx0TXpwWFA5MmFoQ2RSYklBdndmK0RnQ1Zia0oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoKLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5UQTNNRGcwTXpJME1CNFhEVEUzTVRBdwpOREF5TXpJd00xb1hEVEl5TVRBd016QXlNekl3TkZvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFV3TnpBNE5ETXlORENDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVRacHYrVEhleTFXVVRlK21HdmttVzNGWXZzc2l0blo4eG53KytHVlBZNgowUDdhNEhmRGFWdDN1MWZIbW9rbmFqY0k4a3A0ZktaU1lqN0xBNE1aN0hDcG14TWdIRDFyTGJibElQZnQ5dzBzCnFXcTBZbk1GNmRqTHJHWEVjanpJZTdFYVVJUkdKclR1L1NFcjJFZDZsby8veTFYM1Y0bXppMVBXb3pWVEh1WEUKSFBsWHJFbWVmSFFsQ2Zta1MzWXB0TEpZNUc1TmVUa2UwcGIybjJYS0toOEd5Q0RLYysvV3Ivd0ZmYzd5N0tqWQp4Z2VHbEdOWjNMMUFRSVlQemxXWHVCUjVtc3BSMGZVVk1xS1ZXU3VXc1VqbHRIanp3cUY3TzVLV0FuZFNWMzhlCjNkVjhodmJ1WWtPOTViMDg0elk4dXhKMWlXZEFnbklBN21YWU5aOWZONk1DQXdFQUFhTWpNQ0V3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUg3OQplbnB2MEd3Znd5aklHdTBhcWtoRWhQKzloRWJCck5IbkROc3ZEQXFLTXNvRkJFSVc1bkZoNjZ1dkNJTFJ2Y1hEClFYZVNqczFJdHc5NnBLa1hJQkpId210V3RhcWJBYkdTa3BMYzFkNmp6SWVVQklZUjc3akViUE45OEhtNTVqcisKZ0dsV29EZGRBSDY5RUdpVHBDQ0ltaUF1VUdNbHBxQkxDUFBvZms1ZnNTMHBjVXNQeVV5aGNmdHhqRFpiaFJNRQpwdlprT3NEY25jTHRVUWtBM3V6MVd5enhRVWhYWm9QTjZRajhwMXVCU1R2RER0TUlLL1ltU3FFRjFTSGxDZ2lpClpnNlNmVm1HUENOaUZlWC9UMDcxUGtoN1B4b1FVMXI5ZXQ4K0JMbEE0M1NPQzRhMWE1WU1GV2NuSDd5dE52NUIKRHNWMi93N3dkRnBPVi9obTlkYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo='
+ oc create -f -
+ curl -s https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
+ oc process -n ansible-service-broker -p DOCKERHUB_USER=jmrodri -p DOCKERHUB_PASS=HIkyoiHirHi1 -p DOCKERHUB_ORG=ansibleplaybookbundle -p ENABLE_BASIC_AUTH=false -p BROKER_CA_CERT=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTFNRGN3T0RRek1qTXdIaGNOTVRjeE1EQTBNREl6TWpBeVdoY05Nakl4TURBegpNREl6TWpBeldqQW1NU1F3SWdZRFZRUUREQnR2Y0dWdWMyaHBablF0YzJsbmJtVnlRREUxTURjd09EUXpNak13CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN4UDh0Z2ZNV1MzQm1KOGhGSE9IQUEKY0hrRzVHWWczaTYwYVVEZTlENU5nNXJXZlZsSkVnZUhwaWtVeXFnbTVBUVdJeThKZE5kbW85c2QzdEluc0RxMAp2QndyRzBUU1YzaWQ4TlpmVjJ5aTZFdVBxSTVIeGtJQUFaYXM3Y1RlYjlxRC9QVEhQSVlWcy9sdjlsb24zUlV1CnhGZ3RaQU5HcW1XRW9raHkyYnd0MDVDSFdVYUp0cUZGMHM2MzBEajRLbW9XMkpuZUF5cGNlSGlUMDNTZ1JneEcKdmhKbVRaVm53MEVqckVvRUtYTHM1eXdlNk1OT0NUYTh4Ymdkd0hZNHZDb0Uva2I2NFJvelY1cTllSDRkSGFSNQpwZzNMTWVQenBKS1czc1FXbFZjYU9peTNvaGozZkR2emdjMkwxcEJ5TVc2YWN4SlQwcnhnSDlnYmNvSEc2TTg1CkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQXlHWm1pM1NXNHVTUW84cENvNktGL05rejlOSHNhY0lEOHRNdXJUSVczM0VPMwpGY2xNQ0E2RHdwOEs1SFBQdkhUMFJXYWRzczNkWlFoTGFBUFdua0NmVFFidndma2FIdjMvaGN0N2lvWGJHd1pRCk9oODQvUWtGdnRGcU04Mm50eWtCbGcxenFiaHErWVM0K1RNa0VIQWZpL1AwOVpBY2NCdnZybzMzdldXcWFvdDEKQkpGbDM4RjRTdk5vQURmOXRTWFZ5aENpWFl4N3RMQTBUL0tQYnRUUEpTR0tUbW82QzIyaFRqQVZtQkR1S3ZrMwoxUGtTNHVJdklxSnB3RWtjUDB4dzVsZUZyNnVZakN5NCt5azFhdU4vYlhscjFPVERjTC9vUlp1WFluVVhxRkdxCnRIazFSMXlZTHB2bUx0TXpwWFA5MmFoQ2RSYklBdndmK0RnQ1Zia0oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoKLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5UQTNNRGcwTXpJME1CNFhEVEUzTVRBdwpOREF5TXpJd00xb1hEVEl5TVRBd016QXlNekl3TkZvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFV3TnpBNE5ETXlORENDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVRacHYrVEhleTFXVVRlK21HdmttVzNGWXZzc2l0blo4eG53KytHVlBZNgowUDdhNEhmRGFWdDN1MWZIbW9rbmFqY0k4a3A0ZktaU1lqN0xBNE1aN0hDcG14TWdIRDFyTGJibElQZnQ5dzBzCnFXcTBZbk1GNmRqTHJHWEVjanpJZTdFYVVJUkdKclR1L1NFcjJFZDZsby8veTFYM1Y0bXppMVBXb3pWVEh1WEUKSFBsWHJFbWVmSFFsQ2Zta1MzWXB0TEpZNUc1TmVUa2UwcGIybjJYS0toOEd5Q0RLYysvV3Ivd0ZmYzd5N0tqWQp4Z2VHbEdOWjNMMUFRSVlQemxXWHVCUjVtc3BSMGZVVk1xS1ZXU3VXc1VqbHRIanp3cUY3TzVLV0FuZFNWMzhlCjNkVjhodmJ1WWtPOTViMDg0elk4dXhKMWlXZEFnbklBN21YWU5aOWZONk1DQXdFQUFhTWpNQ0V3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUg3OQplbnB2MEd3Znd5aklHdTBhcWtoRWhQKzloRWJCck5IbkROc3ZEQXFLTXNvRkJFSVc1bkZoNjZ1dkNJTFJ2Y1hEClFYZVNqczFJdHc5NnBLa1hJQkpId210V3RhcWJBYkdTa3BMYzFkNmp6SWVVQklZUjc3akViUE45OEhtNTVqcisKZ0dsV29EZGRBSDY5RUdpVHBDQ0ltaUF1VUdNbHBxQkxDUFBvZms1ZnNTMHBjVXNQeVV5aGNmdHhqRFpiaFJNRQpwdlprT3NEY25jTHRVUWtBM3V6MVd5enhRVWhYWm9QTjZRajhwMXVCU1R2RER0TUlLL1ltU3FFRjFTSGxDZ2lpClpnNlNmVm1HUENOaUZlWC9UMDcxUGtoN1B4b1FVMXI5ZXQ4K0JMbEE0M1NPQzRhMWE1WU1GV2NuSDd5dE52NUIKRHNWMi93N3dkRnBPVi9obTlkYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= -f -
service "asb" created
serviceaccount "asb" created
clusterrolebinding "asb" created
clusterrole "asb-auth" created
clusterrolebinding "asb-auth-bind" created
clusterrole "access-asb-role" created
persistentvolumeclaim "etcd" created
deploymentconfig "asb" created
secret "asb-auth-secret" created
configmap "broker-config" created
serviceaccount "ansibleservicebroker-client" created
clusterrolebinding "ansibleservicebroker-client" created
secret "ansibleservicebroker-client" created
route "asb-1338" created
error: unable to recognize servicecatalog.k8s.io/v1alpha1, Kind=ServiceBroker: no matches for servicecatalog.k8s.io/, Kind=ServiceBroker
+ '[' 1 -ne 0 ']'
+ echo 'Error processing template and creating deployment'
Error processing template and creating deployment
+ exit
```

**Comment by karmab** [comment]
tested the PR and it worked for me ( sorry for the delay, thought it allready got merged)
@jmrodri i believe your issue is not related to the script changes, rather something that prevented the deployment of the service broker pods ( lack of resources??)

**Pull request merged**
