### PR TITLE
Bug 1765082: add registry-proxy support, bump bundle-lib

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

After three days of retesting, this does not look like a flake.

**Comment by fabianvf** [comment]
@jmrodri looks like we're starting to get bit by the python2 deprecation. Looks like `more-itertools` dropped python2 support recently: https://github.com/erikrose/more-itertools/issues/355#issuecomment-565474007
which is why the build is failing with a syntax error on `pip install`: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_ansible-service-broker/1253/pull-ci-openshift-ansible-service-broker-release-4.2-operator-molecule-e2e/94#1:build-log.txt%3A309

We can pin the more-itertools version to 5.0.0 and that should get us past it for now

**Comment by jmrodri** [comment]
Closed won't fix

**Pull request closed without merging**
