### PR TITLE
Bug 1772743: Add olm.skipRange to all CSVs and art.yaml (#1257)

### PR DESCRIPTION
**Pull request by fabianvf**
* Bug 1772392: Add olm.skipRange to all CSVs and art.yaml

* Properly set skipRange for 4.1

(cherry picked from commit d8cb6fe7bdeef19b888aa9a01e02701e356f630f)

#### Changes proposed in this pull request

 -
 -
 -

#### Does this PR depend on another PR (Use this to track when PRs should be merged)
depends-on <PR>

#### Which issue this PR fixes (This will close that issue when PR gets merged)
fixes <issue_number>

### CODE REVIEW

**Comment by jmrodri** [comment]
This is failing because we need to add `wheel` package to the `custom-ci-build-root.Dockerfile`. See PR #1260 for an example.

**Comment by bparees** [comment]
this PR will not be cherry-pick-approved until the hold is removed.

**Comment by sdodson** [comment]
@fabianvf cherry-pick-approved withheld due to hold, is this going in or should it be closed?

**Comment by jmrodri** [comment]
@sdodson this is supposed to go in, but we have a weird issue where the CI job is NOT picking up the Dockerfile change from this PR. @wking this is another one of those PRs where it seems the build is caching something.

**Comment by sdodson** [comment]
There's a known image build cache issue that's triggering these failures.
/override ci/prow/fmtcheck
/override ci/prow/operator-molecule-olm-e2e
/override ci/prow/test
/override ci/prow/operator-molecule-e2e
/override ci/prow/lint
/override ci/prow/images
/override ci/prow/fmt
/override ci/prow/vet
/override ci/prow/build

**Pull request merged**
