### PR TITLE
switching dependency management from glide to dep

### PR DESCRIPTION
**Pull request by shawn-hurley**
**Describe what this PR does and why we need it**:
Move from [glide](https://github.com/Masterminds/glide) to [dep](https://github.com/golang/dep)

Although dep was not added to the core toolchain for go 1.10 I still think that it is worth moving to for dependancy management for the errors and help it has for updating and vendor bumps.

### CODE REVIEW

**Comment by rthallisey** [comment]
Does ```make vendor``` need to change?

**Comment by jmrodri** [comment]
```
$ make vendor                                                   
[ERROR] Failed to find glide.yaml file in directory tree: Cannot resolve parent of /                                                
make: *** [Makefile:18: vendor] Error 2                           
```

**Comment by jmrodri** [comment]
The problem I'm hitting is that it doesn't work with my symlink setup.

`/home/devel/jesusr/dev/cap/ansible-service-broker` - real location, git cloned
`/home/devel/jesusr/dev/src/github.com/openshift/ansible-service-broker` - symlink to the above
`/home/devel/jesusr/dev/` - `GOPATH` value

If I run `dep ensure` inside the symlink path `cd /home/devel/jesusr/dev/src/github.com/openshift/ansible-service-broker`, then `dep ensure` will complain with the following error:

```
both /home/devel/jesusr/dev/src/github.com/openshift/ansible-service-broker and /home/devel/jesusr/dev/cap/ansible-service-broker are in the same GOPATH /home/devel/jesusr/dev
```
If I try to run `dep ensure` from the checked out path, `/home/devel/jesusr/dev/cap/ansible-service-broker` it complains I'm not in the project :) 

There are quite a few of symlink issues with dep :) 

https://github.com/golang/dep/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+symlink

https://github.com/golang/dep/issues/1723

So I'm going to mark this as approved since it seems it's my current setup.

**Comment by jmrodri** [comment]
So if i clone the project into a path NOT in my `GOPATH` it works with symlink
real directory with project: `/home/jesusr/ansible-service-broker`
`GOPATH`: `/home/jesusr/dev/`
symlink: `/home/jesusr/dev/src/github.com/openshift/ansible-service-broker -> /home/jesusr/ansible-service-broker/`

```
$ cd $GOPATH/src/github.com/openshift/ansible-service-broker/
$ $ dep ensure -v
Gopkg.lock was already in sync with imports and Gopkg.toml
(1/75) Wrote github.com/gorilla/mux@v1.4.0                                                               
(2/75) Wrote github.com/golang/glog@44145f04b68cf362d9c4df2182967c2275eaefed
(3/75) Wrote github.com/PuerkitoBio/purell@v1.0.0                                                        
(4/75) Wrote github.com/gorilla/handlers@v1.2.1     
...
(72/75) Wrote golang.org/x/sys@95c6576299259db960f6c5b9b69ea52422860fce                                  
(73/75) Wrote golang.org/x/text@b19bf474d317b857955b12035d2c5acb57ce8b01                                 
(74/75) Wrote github.com/openshift/api@master       
(75/75) Wrote k8s.io/kubernetes@v1.9.1              
```

**Comment by jmrodri** [comment]
Capturing for posterity, this https://github.com/golang/dep/issues/1429 is the issue I was hitting on my desktop causing the hang.

**Comment by djzager** [comment]
Thank you for testing out symlinks @jmrodri that would have been painful, thankfully I'm in the working category.

**Pull request merged**
