### PR TITLE
Bug 1506713 - handle updatable enum parameters properly in schema output

### PR DESCRIPTION
**Pull request by jmontleon**
**Describe what this PR does and why we need it**:

Changes proposed in this pull request
 - Make sure parameter types are specified for update
 
**Does this PR depend on another PR (Use this to track when PRs should be merged)**
depends-on N/A

**Which issue this PR fixes (This will close that issue when PR gets merged)**
fixes N/A

### CODE REVIEW

**Comment by jmrodri** [comment]
@jmontleon needs a bugzilla

**Comment by jmontleon** [comment]
@jmrodri BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1506713

**Comment by jmrodri** [comment]
Wrong PR title, needs to be `Bug # - comment` I will update it.

**Comment by jmrodri** [comment]
Please add a unit test to `pkg/broker/util_test.go`. Verify the `Maxlength` change, pattern and the enum.

**Comment by jmontleon** [comment]
@jmrodri missing anything else?

**Pull request merged**
