### PR TITLE
include FQName in spec logging, ID isn't useful enough

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by jmrodri** [comment]
```
time="2018-07-24T20:46:32Z" level=debug msg="spec '595db86e75325f430afa4fa3f7d69af9|dh-iscsi-demo-target-apb' needs to be added"
time="2018-07-24T20:46:32Z" level=debug msg="spec '880ef3b4ba5fa8d80908e9974228e603|dh-awx-apb' needs to be added"
time="2018-07-24T20:46:32Z" level=debug msg="spec 'fd9b21a9caa8bf8b42b27bb0c90d3b74|dh-virtualization' needs to be added"
time="2018-07-24T20:46:32Z" level=debug msg="spec 'aff6d7bb9c7f57c9ce8b742228e4caa3|dh-es-apb' needs to be added"
time="2018-07-24T20:46:32Z" level=debug msg="spec 'd4684c1b61cd094af9aa6ec4a90b4d69|dh-demo-app-apb' needs to be added"
```

```
time="2018-07-24T20:46:32Z" level=info msg="add spec: 0e991006d21029e47abe71acc255e807|dh-pyzip-demo-apb"
time="2018-07-24T20:46:32Z" level=info msg="add spec: 3f85c20e073a9c761d3f8560b4c5180b|dh-demo-ext-api-apb"
time="2018-07-24T20:46:32Z" level=info msg="add spec: c4ef25f81a0c275c8f1bee1b736f3068|dh-mssql-apb"
time="2018-07-24T20:46:32Z" level=info msg="add spec: f755257efed3e3d43c8b82afd0db1181|dh-prometheus-apb"
time="2018-07-24T20:46:32Z" level=info msg="add spec: 6df7afbd132c094704b4a8bfd44378c0|dh-manageiq-apb"
time="2018-07-24T20:46:32Z" level=info msg="add spec: eebf92c7670f30007a4b8db3a8166d5c|dh-thelounge-apb"
```

**Comment by jmrodri** [comment]
Before the change it only included the ID which is different than how we log the spec in other places which just use the FQName.

**Comment by jmrodri** [comment]
I can also remove the id altogether if that is preferred. @djzager

**Comment by alaypatel07** [comment]
My 2 cents:

1. There is another [place](https://github.com/openshift/ansible-service-broker/blob/c0cd92a3e8f18f9ebb7964e9d2c12e3861ce38d6/pkg/broker/broker.go#L346) where I have used spec id for logging information. In retrospect, I feel this logging information is not very helpful, since converting spec from list to map will rarely go wrong. Replacing 
```
func convertSpecListToMap(specs []*bundle.Spec) map[string]*bundle.Spec {
        specMap := make(map[string]*bundle.Spec)
         for _, spec := range specs {
                 log.Debugf("spec '%v' converted to map", spec.ID)
                 specMap[spec.ID] = spec
         }
         return specMap
}
```

with 
```
func convertSpecListToMap(specs []*bundle.Spec) map[string]*bundle.Spec {
        log.Debugf("converting []*Spec to SpecManifest ")
        specMap := make(map[string]*bundle.Spec)
        for _, spec := range specs {
                specMap[spec.ID] = spec
        }
        log.Debugf("converting []*Spec to SpecManifest successful")
        return specMap
}
````
might be more concise and appropriate.

2. An admin can use the spec ID from logs to run `oc edit bundle spec_id` and force the `delete` flag to true/false. Hence +1 for `id|spec.FQName` in the logs

**Pull request merged**
