### PR TITLE
adding ability to print requests to log if config value is set.

### PR DESCRIPTION
**Pull request by shawn-hurley**
This change might need to also change catasb for the broker config yaml changes.

### CODE REVIEW

**Comment by shawn-hurley** [comment]
[Add a --verbose or --debug option to Ansible Service Broker to aid in troubleshooting issues.](https://trello.com/c/3Si48CdN/287-add-a-verbose-or-debug-option-to-ansible-service-broker-to-aid-in-troubleshooting-issues)

**Comment by eriknelson** [comment]
Built and tried to test this PR tonight. I deployed and tested a broker from this branch with no issue, configured to *not* print output. I had trouble configuring the template to print output. I'd like to see that before I ACK, but the patch looks good, so that's on me. I will continue to test tomorrow.

Thanks @shawn-hurley, long overdue.

**Comment by eriknelson** [comment]
ACK! Works great, sample output:

```
[2017-06-15T16:51:55.796Z] [INFO] Request: "PUT /v2/service_instances/748647cb-fbe9-4cc3-b641-b84a97221905?accepts_incomplete=true HTTP/1.1\r\nHost: asb-1338-ansible-service-broker.172.17.0.1.nip.io\r\nAccept-Encoding: gzip\r\nAuthorization: Basic Og==\r\nContent-Length: 292\r\nContent-Type: application/json\r\nForwarded: for=::ffff:172.17.0.2;host=asb-1338-ansible-service-broker.172.17.0.1.nip.io;proto=http\r\nUser-Agent: Go-http-client/1.1\r\nX-Broker-Api-Version: 2.11\r\nX-Forwarded-For: ::ffff:172.17.0.2\r\nX-Forwarded-Host: asb-1338-ansible-service-broker.172.17.0.1.nip.io\r\nX-Forwarded-Port: 80\r\nX-Forwarded-Proto: http\r\n\r\n{\"organization_guid\":\"eee504ac-51ea-11e7-b624-64006a6f8a4f\",\"plan_id\":\"4c10ff42-be89-420a-9bab-27a9bef9aed8\",\"service_id\":\"55c53a5d-65a6-4c27-88fc-e027410b1882\",\"space_guid\":\"eee504ac-51ea-11e7-b624-64006a6f8a4f\",\"accepts_incomplete\":true,\"context\":{\"platform\":\"kubernetes\",\"namespace\":\"dd\"}}"
[2017-06-15T16:51:55.799Z] [INFO] ASYNC provisioning in progress
```

**Comment by eriknelson** [comment]
Going to follow this up with some small changes to catasb to support configuration.

**Comment by eriknelson** [comment]
https://github.com/fusor/catasb/pull/71

**Pull request merged**
