### PR TITLE
Add auth_type params to our template

### PR DESCRIPTION
**Pull request by dymurray**
**Describe what this PR does and why we need it**:
Adds `auth_type` to the default registry config.

Changes proposed in this pull request
 - Add auth_type and auth_name to deploy template

### CODE REVIEW

**Comment by jmrodri** [comment]
@dymurray was there a bugzilla for this PR?

**Comment by dymurray** [comment]
@jmrodri no BZ for this PR. It came from Tommy Hughes hoping to use this template with the RHCC registry. It can wait to merge if needed.

**Comment by eriknelson** [comment]
I've rerun the build a couple times and it looks like it's timing out on a provision during integration testing. I can't tell if this is legitimate or not, but is the purpose of this change just to parameterize some values? I see two new keys in the registry config that were not there before. Is that causing problems somewhere with the broker?

**Comment by rthallisey** [comment]
let's rebase and pickup the latest changes. Maybe we'll get a different result.

**Comment by eriknelson** [comment]
Restarted the build since we've been seeing a lot of timeouts. @dymurray, this still belongs in master as-is, correct?

**Comment by dymurray** [comment]
I'm closing this PR since the template is mainly used for upstream integration with Dockerhub. I am going to add documentation on using this template with RHCC instead.

**Pull request closed without merging**
