### PR TITLE
Use docker cp instead of mounting host volume

### PR DESCRIPTION
**Pull request by djzager**

### CODE REVIEW

**Comment by djzager** [comment]
@PhilipGough I'm hoping you can tell me if this changes how it was supposed to work. I suspect, that I would have needed to give write permissions to the volume I was sharing (`/tmp/artifact`) in order for it to work.

**Comment by djzager** [comment]
```
➜  ansible-service-broker git:(master) ✗ make deploy
docker run --rm -v "/home/dzager/go/src/github.com/openshift/ansible-service-broker/build":/tmp/artifact docker.io/philipgough/dlv:centos cp /go/bin/dlv /tmp/artifact
cp: cannot stat '/tmp/artifact/dlv': Permission denied
make: *** [Makefile:80: build-dev] Error 1
```

**Comment by PhilipGough** [comment]
Ok, will test this change tomorrow to ensure it works on osx. It looks fine

**Comment by PhilipGough** [comment]
@djzager change works fine on osx. I've created a pr to your branch https://github.com/djzager/ansible-service-broker/pull/1 which fixes a minor issue that arose when testing this.

Thanks

**Pull request merged**
