### PR TITLE
Bug 1727997: fix pagination url, bump bundle-lib (#1242)

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by bparees** [comment]
@jmrodri @shawn-hurley not sure what the `hold` was added for, but needs an lgtm before being considered for z-stream merge.

**Comment by jmrodri** [comment]
I updated the bugs correctly.

**Comment by jmrodri** [comment]
I believe this is waiting on the 4.2 BZ to go to VERIFIED. I've already double-checked to make sure the bug states are correct with eparis.

**Comment by bparees** [comment]
yeah, this needs https://bugzilla.redhat.com/show_bug.cgi?id=1727996 to go verified before it can be cherry-pick approved.  You can help the process along by doing a /bugzilla refresh once you see the BZ go verified, but i'll check back on monday (last day to merge for this particular Z release)

**Pull request merged**
