### PR TITLE
Accept ints from exported credentials

### LINKED ISSUE #335: Non-quoted numeric bind credentials cause other bind credentials to disappear from secrets.
> ### Bug: Non-quoted numeric bind credentials cause other bind credentials to disappear from secrets.

**What happened**:

1. Ran a MySQL APB containing an `asb_encode_binding` command including a port number.
```
- name: Encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: "mysql"
      DB_PASSWORD: "{{ MasterUserPassword }}"
      DB_NAME: "{{ DBName }}"
      DB_HOST: "{{ rds_endpoint_address }}"
      DB_PORT: "{{ PortNumber }}"
      DB_USER: "{{ MasterUsername }}"
```
 2. Created a hello-world APB to bind to the database 
 3. Binded the hello-world APB to database
 4. Inspected the secret created as a result of bind
 5. Noticed that secret created only contained the first 3/6 encoded fields

 6. Added escaped quotes around port number encode line
```
      DB_PORT: "\"{{ PortNumber }}\""
```
 7. Re-deployed MySQL APB, hello-world APB
 8. All bind credentials showed up as expected

 
**What you expected to happen**:
Same as above but expected all fields to show up in secret without needing to put quotes around DB_PORT value. Alternatively, would have been useful to receive an error message explaining the issue and workaround.

### PR DESCRIPTION
**Pull request by eriknelson**
**Describe what this PR does and why we need it**:
Changes proposed in this pull request
- Fixes issue preventing broker from handling integer credentials

**Which issue this PR fixes (This will close that issue when PR gets merged)**
fixes #335

### CODE REVIEW

**Comment by shawn-hurley** [comment]
ACK

**Comment by jmrodri** [comment]
In master the unit test will result in a failure (expected).
```
=== RUN   TestInt
--- FAIL: TestInt (0.00s)
        util.go:113: 
                ext_creds_test.go had error on line 37
                Message: port does not match

```

**Comment by jmrodri** [comment]
With your fix it passes:
```
=== RUN   TestInt
--- PASS: TestInt (0.00s)
```

**Comment by jmrodri** [comment]
What's interesting is that it parses it as a float64 not an int.

**Comment by jmrodri** [comment]
What's also weird is that `func decodeOutput(output []byte) (map[string]string, error)` has returned `map[string]string` since the beginning, why are things breaking now?

**Pull request merged**
