### PR TITLE
Remove the output of params used for oc login

### PR DESCRIPTION
**Pull request by rthallisey**
oc login is sending the parameters used for oc login to std out.

### CODE REVIEW

**Comment by eriknelson** [comment]
@rthallisey Looks like this won't build due to the unused strings import.

**Comment by rthallisey** [comment]
Thanks @eriknelson. The new makefile run had me thinking I tested it.

**Comment by eriknelson** [comment]
ACK! (pending travis)

**Comment by rthallisey** [comment]
[Security cleanup of asb code](https://trello.com/c/FevyaWvn/280-security-cleanup-of-asb-code)

**Pull request merged**
