### PR TITLE
broker-config changed

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by jmrodri** [comment]
This fixes the tito rpm build.

**Comment by jmontleon** [comment]
I think @shawn-hurley is working on a PR that changes everything back to config.yaml. He should be submitting it shortly. Moving the spec to the root dir in the repo also broke the copr builds. I am working on fixing that.

**Comment by shawn-hurley** [comment]
please look at PR #218

**Comment by jmrodri** [comment]
Closing in favor of PR #218

**Pull request closed without merging**
